/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_aa_jinjikk_proj_LedActivity */

#ifndef _Included_com_example_aa_jinjikk_proj_LedActivity
#define _Included_com_example_aa_jinjikk_proj_LedActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_aa_jinjikk_proj_LedActivity
 * Method:    LEDControl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_aa_jinjikk_1proj_LedActivity_LEDControl
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
